get_parameters <-
structure(function#L-moment parameter estimates for exceedance curve fitting.
### estimate the parameters of a log Pearson III or 3-parameter lognormal 
### distribution.
(flowdata,
### flow duration data to be used for fitting, as created by get_peakavg(). 
### NA values are automatically removed.
distr=c('lp3', 'ln3')
### distribution to be fitted, either log Pearson III ('lp3') or lognormal ('ln3').
){
##details<< The function uses the lmom package to compute method of L-moment 
##estimates. See lmomco package documentation for information on definitions 
##of the log Pearson III and 3-parameter lognormal distributions.
  distr = match.arg(distr, c('lp3', 'ln3'))
  parameters_from_lmoments = function(d, distr){
    if(distr=='lp3'){
	  # log Pearson III distribution
      # take log of data
      ld = log10(d)
      lmoms = lmom.ub(ld)
	  moms = lmom2par(lmoms, type='pe3')
    } else {
	  # 3-parameter lognormal distribution
      lmoms = lmom.ub(d)
	  moms = lmom2par(lmoms, type='ln3', zeta=0)
    }
    return(moms)
  }
  # collect parameter estimates for each flow duration
  paramdata = data.frame(dummy=rep(NA, 3))
  for(n in names(flowdata)){
    prms = parameters_from_lmoments(flowdata[[n]][!is.na(flowdata[[n]])], distr)
    paramdata[n] = prms$para
  }
  rownames(paramdata) = names(prms$para)
  return(paramdata[names(flowdata)])
### a dataframe of similar construction to one generated by get_peakavg(). 
### Column names are flow durations, named rows are the distribution parameters.
}, ex = function(){
data(workedexample)
get_parameters(usgs.fd, distr='lp3')
get_parameters(usgs.fd, distr='ln3')
})
