plot_countexc <-
structure(function#Box plot and density
### Create box plots for multiple flow durations
(d,
### flow data generated by get_forecast() or to_*year()
flowexceeds
### vector of flow magnitudes for exceedance counts
){
  flowcols = !(grepl('WYD', names(d)) | grepl('GMT', names(d)))
  d['month'] = format(d$GMT, "%b")
  # start plotting
  pd = melt(d, id.var=c('GMT', 'WYD', 'month'),
            variable.name='trace', value.name='flow')
  pd['flow.exceeds'] = NA  
  for(f in sort(flowexceeds))
    pd[pd$flow > f & !is.na(pd$flow), 'flow.exceeds'] = f
  pd['month'] = factor(pd$month, levels=unique(pd$month))
  pd['flow.exceeds'] = factor(pd$flow.exceeds, levels=flowexceeds)
  # need to reform data again
  npd = NULL
  for(i in flowexceeds)
    npd = rbind(npd, data.frame(month=unique(d$month), flow.exceeds=i))
  npd['month'] = factor(npd$month, levels=unique(d$month))
  npd['flow.exceeds'] = factor(npd$flow.exceeds, levels=sort(flowexceeds))
  # make the counts
  npd['count'] = NA
  for(m in levels(npd$month))
    for(i in levels(npd$flow.exceeds))
	  npd[npd$month==m & 
	      npd$flow.exceeds==i, 'count'] = sum(pd$month==m &
		                                      pd$flow > as.numeric(i),
											  na.rm=TRUE)
  p = ggplot(npd, aes(x=month, y=count, fill=flow.exceeds)) + 
      geom_bar(position='identity', stat='identity', color='black') +
	  scale_fill_brewer(palette='OrRd') + xlab('')
  return(p)
### a ggplot box plot  
}, ex = function(){
data(hspftraces)
hspf.wyear = split_by_wateryear(hspftraces)
plot_countexc(hspf.wyear, flowexceeds=c(150, 200, 500))
})
