plot_trace <-
structure(function#Plot a single ESP trace.
### plot an individual trace.
(d, 
### a dataframe generated by get_forecast() or split_by_*year(get_waterdata() ).
colname
### the column name of the trace to be plotted.
){
  nd = data.frame(GMT=d$GMT, WYD=d$WYD, flow=d[[colname]])
  p = ggplot(nd, aes(x=GMT, y=flow)) + geom_line() + ggtitle(colname) +
	  scale_x_date('', breaks=scales::date_breaks("months"), 
                   labels=scales::date_format("%b"))
  return(p)
### a ggplot plot.
}, ex = function(){
data(esptraces)
plot_trace(esptraces, "AHOC1.2000")

# can also use this function to plot raw timeseries
data(usgstraces)
require(ggplot2)
plot_trace(usgstraces, na.omit('flow')) + scale_x_date('', breaks=scales::date_breaks("years"), labels=scales::date_format("%Y")) +theme (axis.text.x = element_text(angle=45, hjust=1))
})
