plot_peakflows <-
structure(function#Flow duration histograms
### Plot histograms for each flow duration
(fd,
### Flow duration data generated by get_peakavg()
logscale=TRUE,
### Logical: plot flows on log scale?
count=TRUE,
### Logical: plot counts (histogram) instead of density?
facet=TRUE
### Logical: Facet the data by flow duration?
){
  pd = melt(fd, variable.name='flow.duration', value.name='flow')
  p = ggplot(pd, aes(x=flow, fill=flow.duration)) + 
      scale_fill_brewer(palette="Set1")
  if(count)
    p = p + geom_histogram(color='black', position='stack')
  else
    if(facet)
      p = p + geom_density(color='black', alpha=1)
    else
      p = p + geom_density(color='black', alpha=0.2)
  if(facet)
    p = p + facet_wrap(~flow.duration)
  if(logscale)
    p = p + scale_x_log10()
  return(p)
### ggplot of histograms faceted by flow duration
}, ex = function(){
data(esptraces)
esp.ahoc = subset_forecast(esptraces, location='AHOC1')
esp.fd = get_peakavg(esp.ahoc, c(1,3,7))
plot_peakflows(esp.fd)
plot_peakflows(esp.fd, facet=FALSE, count=FALSE)
})
