predict_exceedance <-
structure(function#Calculate exceedance curves.
### generate fitted exceedance curves for plotting.
(flowdata,
### flows for which exceedance probabilities. Column names must
### match columns in argument parameterdata.
parameterdata, 
### dataframe of parameters as generated by get_parameters().
distr
### The distribution corresponding to the parameter estimates. Can be either
### log Pearson III ('lp3') or 3-parameter lognormal ('ln3').
){
  distr = match.arg(distr, c('lp3', 'ln3'))
  if(distr=='lp3'){
	distype = 'pe3'
	cdffun = function(x, ...) par2cdf(log10(x), ...)
  } else {
    distype = 'ln3'
	cdffun = par2cdf
  }
  # predict exceedance probabilities
  pexc = flowdata
  pexc[,] = NA
  for(n in names(flowdata)){
    # coerce data into proper format
	prms = parameterdata[[n]]
	names(prms) = rownames(parameterdata)
	paramobj = vec2par(prms, distype)
    pexc[n] = 1 - cdffun(flowdata[[n]], paramobj)
  }	
  return(pexc)
### a dataframe for plotting exceedance curves for each flow duration. Rows
### correspond to probability values contained in column 'p.exceedance'. Column 
### names are the flow durations.
}, ex = function(){
data(workedexample)
# compare predictions using L-moment and refined estimates
predict_exceedance(usgs.fd, usgs.lp3, distr='lp3')
predict_exceedance(usgs.fd, usgs.lp3.ref, distr='lp3')

# predict new flow values
newflows = data.frame(c(1000, 2000), c(1000, 2000))
names(newflows) = c('1.day.flow', '3.day.flow')
predict_exceedance(newflows, usgs.lp3.ref, distr='lp3')
})
