subset_waterdata <-
structure(function#Subset downloaded USGS flow data.
### subset waterdata by interval.
(d, 
### a dataset generated by split_by_wateryear() or split_by_calendaryear().
sc=c('WYD', 'GMT'), 
### search column to use for subsetting by date.
startdate=NULL, 
### the first day of the interval, either 'MM-DD' string or 3-digit WYD.
enddate=NULL
### the last day of the interval, same format as startdate.
){
  sc = match.arg(sc, c('WYD', 'GMT'))
  # check startdate, endate
  if(is.null(startdate))
	if(sc == 'WYD')
	  startdate = d$WYD[1]
	else
	  startdate = substr(d$GMT[1], 6, 10)
  if(is.null(enddate))
	if(sc == 'WYD')
	  enddate = d$WYD[ncol(d)]
	else
	  enddate = substr(d$GMT[nrow(d)], 6, 10)
  if(sc == 'WYD'){
    if(substr(d$GMT[1], 1, 4) == '0000')
      stop('Input data was split by calendar year. Cannot subset the data by WYD.')	
    # startdate, enddate are integers
	rowmask = d$WYD >= startdate & d$WYD <= enddate
  } else {
    # startdate, enddate are format 'MM-DD'
    startmonth = as.numeric(substr(startdate, 1, 2))
	endmonth = as.numeric(substr(enddate, 1, 2))
    if(substr(d$GMT[1], 1, 4) == '0000'){
	  # data was generated using split_by_calendaryear
	  if(startmonth > endmonth)
	    stop('Intervals spanning December 31 can only be accommodated if ',
	       'data is formatted using split_by_wateryear().')
	  startyear = '0000'
	  endyear = '0000'
	} else if(startmonth < 10 & endmonth > 9){
	  stop('Intervals spanning September 30 can only be accommodated if ',
	       'data is formatted using split_by_calendaryear().')
    } else if(startmonth > endmonth){
	  # interval spans New Years Day (two years)
	  startyear = '0003'
	  endyear = '0004'
	} else {
	  # interval is contained within one year
	  if(endmonth < 10){
	    startyear = '0004'
		endyear = '0004'
	  } else if(startmonth > 9){
	    startyear = '0003'
		endyear = '0003'	  
	  }
    }
	# construct the date intervals
	startinterval = as.Date(paste(startyear, '-', startdate, sep=''))
	endinterval = as.Date(paste(endyear, '-', enddate, sep=''))
	rowmask = d$GMT >= startinterval & d$GMT <= endinterval
  }
  return(d[rowmask, ])
### a subset of the original dataframe.
}, ex = function(){
data(usgstraces)
usgs.wyear = split_by_wateryear(usgstraces)
subset_waterdata(usgs.wyear, sc='GMT', startdate='11-01', enddate='03-31')
subset_waterdata(usgs.wyear, sc='WYD', startdate=32, enddate=182)

data(hspftraces)
hspf.cyear = split_by_calendaryear(hspftraces)
subset_waterdata(hspf.cyear, sc='GMT', startdate='01-01', enddate='06-30')

## Not run:
## # will produce errors
## subset_waterdata(hspf.cyear, sc='WYD', startdate=32, enddate=182)
## subset_waterdata(arroyohondo.wyear, sc='GMT', startdate='09-25', enddate='10-05')
## subset_waterdata(hspf.cyear, sc='GMT', startdate='12-25', enddate='01-05')
## End(Not run)
})
