get_ppositions <-
structure(function#Cunnane plotting positions.
### calculate plotting positions for empirical cdf.
(pafdata, 
### a data frame generated by get_peakavg().
alpha=0.4
### shape parameter, default is 0.4.
##references<< Cunnane 1978, J. Hydrol. 37:205-222
##Helsel and Hirsch, Statistical Methods in Water Resources, USGS.
){
  ppositions = function(d, a){
    # helper function to calculate plotting position
    # get ranks
    rankd = rank(d)
    # calculating plotting position using ranks
    ppos = (rankd - a)/(length(rankd) + 1 - 2*a)
    return(ppos)  
  }
  # initialize output data frame
  pposdata = pafdata
  pposdata[,] = NA
  # calculate plotting positions. Output is P(X >= x)
  for(j in seq(ncol(pafdata)))
    pposdata[, j] = 1 - ppositions(pafdata[, j], alpha)
  return(pposdata)
### a data frame of size pafdata containing the plotting 
### positions of observations for each record.
}, ex = function(){
#  d1 = add_wateryear(get_forecast(as.Date(Sys.time()) ))
#  d2 = split_by_calendaryear(add_wateryear(get_waterdata(startdate='2010-10-01')))
#  p1 = get_peakavg(d1, c(1,3,7,15,30,60,90))
#  p2 = get_peakavg(d2, c(1,3,7,15), na.rm=TRUE)
#  get_ppositions(p1)
#  get_ppositions(p2, 0.4)
})
