get_ppositions <-
structure(function#Cunnane plotting positions.
### calculate plotting positions for empirical cdf.
(pafdata, 
### a data frame generated by get_peakavg().
alpha=0.4
### shape parameter, default is 0.4.
##references<<Cunnane 1978, J. Hydrol. 37:205-222
##Helsel and Hirsch, Statistical Methods in Water Resources, USGS.
){
  ppositions = function(d, a){
    # helper function to calculate plotting position
    # get ranks
    rankd = rank(d)
    # calculating plotting position using ranks
    ppos = (rankd - a)/(length(rankd) + 1 - 2*a)
    return(ppos)  
  }
  # initialize output data frame
  pposdata = pafdata
  pposdata[,] = NA
  # calculate plotting positions. Output is P(X >= x)
  for(j in seq(ncol(pafdata)))
    pposdata[, j] = 1 - ppositions(pafdata[, j], alpha)
  return(pposdata)
### a data frame of size pafdata containing the plotting 
### positions of observations for each record.
}, ex = function(){
data(esptraces)
esp.ahoc = subset_forecast(esptraces, location='AHOC1')
peakflows = get_peakavg(esp.ahoc)
get_ppositions(peakflows, 0.4) # Cunnane (default)
get_ppositions(peakflows, 0) # Weibull
})
