get_excurves <-
structure(function#Calculate exceedance curves.
### generate fitted exceedance curves for plotting.
(parameterdata, 
### dataframe of parameters as generated by get_parameters().
distr, 
### The distribution corresponding to the parameter estimates. Can be either
### log Pearson III ('lp3') or 3-parameter lognormal ('ln3').
probs=c(seq(0.002, 0.019, 0.001), seq(0.02, 0.99, 0.01))
### the quantiles used to generate the curve.
){
  distr = match.arg(distr, c('lp3', 'ln3'))
  if(distr=='lp3'){
    pfmt = function(x) list(type='pe3', para=x, source='parpe3')
	distype = 'pe3'
	quafun = function(...) 10^(par2qua(...))
  } else {
    pfmt = function(x) list(type='ln3', para=x, zeta=0, source='parln3')
    distype = 'ln3'
	quafun = par2qua
  }
  curvedata = data.frame(p.exceedance=probs)
  # generate curve for each flow duration
  for(n in names(parameterdata)){
    # coerce data into proper format
	prms = parameterdata[[n]]
	names(prms) = rownames(parameterdata)
    #paramobj = pfmt(prms)
	paramobj = vec2par(prms, distype)
    curvedata[n] = quafun(1 - probs, paramobj)
  }	
  rownames(curvedata) = curvedata[['p.exceedance']]
  return(curvedata)
### a dataframe for plotting exceedance curves for each flow duration. Rows
### correspond to probability values contained in column 'p.exceedance'. Column 
### names are the flow durations.
}, ex = function(){
#
})
