get_peakavg <-
structure(function#Calculate peak flow durations
### get the peak average flows for many flow records.
(d, 
### a dataframe generated by get_forecast() or get_waterdata().
flowduration=c(1,3,7,15,30,60,90,120,183)
### a vector of window sizes for calculating moving averages.
){
##details<< the function uses the get_flowavg() function in package 'zoo' to
##compute flow duration timeseries. The maximum value of each averaged
##timeseries is the peak flow for that flow duration.
  peakavg = function(obs, sizes){
    # helper function to get maximum values from moving window averages
    # get peak flow for each value in sizes
    rollingmean = function(x, k)
      as.numeric(filter(x, rep(1/k, k), sides=1))
    maxes = rep(NA, length(sizes))
    # take max of each moving window average result
    for(r in seq(length(sizes)))
      maxes[r] = suppressWarnings(max(rollingmean(obs, sizes[r]), 
	                                  na.rm=TRUE))
	maxes[maxes == -Inf] = NA
    return(maxes)
  }
  # get flow columns
  cols = names(d)[!(grepl('GMT', names(d)) | grepl('WYD', names(d)))]
  # create results dataframe
  maf = data.frame(flow.duration=flowduration)
  # get maxavg flows for each record
  for(n in cols)
    maf[n] = peakavg(d[[n]], flowduration)
  # transpose data for better table viewing
  maftable = as.data.frame(t(maf[, seq(2, ncol(maf))]))
  names(maftable) = paste(maf$flow.duration, '.day.flow', sep='')
  return(maftable)
### a dataframe.
}, ex = function(){
data(esptraces)
esp.ahoc = subset_forecast(esptraces, location='AHOC1')
get_peakavg(esp.ahoc, c(1,7,15,30,60))
})
