plot_curves <-
structure(function#Plot empirical and fitted exceedance curves.
### plot the exceedance curves and empirical data.
(flowdata, 
### flow data generated by get_peakavg().
ppos, 
### plotting positions generated by get_ppositions().
curvedata,
### fitted curves generated by get_excurves().
distr,
### the distribution used to generate the fitted curves.
units=c('cf', 'af'),
### the units to be used for displaying flow. Options are cubic feet ('cf')
### or acre-feet ('af').
logscale=TRUE
### logical: display log 10 scale on y-axis?
){
  units = match.arg(units, c('cf', 'af'))
  # helper function for units
  if(units == 'af')
    convert = function(x) x*86400/43560
  else
    convert = function(x) x*86400
  # prepare empirical data
  emp = NULL
  for(n in names(flowdata))
    emp = rbind(emp, data.frame(p.exceedance=ppos[[n]], volume=flowdata[[n]], 
	            flow.duration=n))
  emp['volume'] = convert(emp$volume)
  # prepare fitted data
  fit = melt(curvedata, id.var='p.exceedance', variable.name='flow.duration', 
             value.name='volume')	
  fit['volume'] = convert(fit$volume)
  # plot both
  p = ggplot(NULL, aes(x=p.exceedance, y=volume, color=flow.duration)) + 
      geom_line(data=fit) + geom_point(data=emp) + ggtitle(distr) + 
	  scale_x_reverse('Probability of exceedance', limits=c(1, 0)) + 
	  scale_color_brewer(palette="Set1") 
  if(logscale)
    p = p + scale_y_log10(paste('Volume (', units, ')', sep=''))
  else
    p = p + scale_y_continuous(paste('Volume (', units, ')', sep=''))
  return(p)
### a ggplot2 plot.
}, ex = function(){
#
})
