plot_curves <-
structure(function#Plot empirical and fitted exceedance curves.
### plot the exceedance curves and empirical data.
(flowdata=NULL, 
### flow data generated by get_peakavg().
ppos=NULL,
### plotting positions generated by get_ppositions().
curvedata=NULL,
### fitted curves generated by get_excurves().
distr=NULL,
### the distribution used to generate the fitted curves.
units=c('af', 'cf'),
### the units to be used for displaying flow. Options are cubic feet ('cf')
### or acre-feet ('af').
logscale=TRUE
### logical: display log 10 scale on y-axis?
){
  units = match.arg(units, c('af', 'cf'))
  # helper function for units
  if(units == 'af')
    convert = function(x) x*86400/43560
  else
    convert = function(x) x*86400
  p = ggplot(NULL, aes(x=p.exceedance, y=volume, color=flow.duration)) + 
      ggtitle(distr) + scale_color_brewer(palette="Set1") +
	  scale_x_reverse('Probability of exceedance', limits=c(1, 0))
  if(!is.null(curvedata)){
    # prepare fitted data
    fit = melt(curvedata, id.var='p.exceedance', value.name='volume',
	           variable.name='flow.duration')
    fit['volume'] = convert(fit$volume)
	p = p + geom_line(data=fit)
  }
  if(!(is.null(flowdata) | is.null(ppos))){
    # prepare empirical data
    emp = NULL
    for(n in names(flowdata))
      emp = rbind(emp, data.frame(p.exceedance=ppos[[n]], 
	                              volume=flowdata[[n]], 
								  flow.duration=n))
    emp['volume'] = convert(emp$volume)
    p = p + scale_fill_brewer(palette="Set1") + 
	    geom_point(data=emp)
  }
  if(logscale)
    p = p + scale_y_log10(paste('Volume (', units, ')', sep=''))
  else
    p = p + scale_y_continuous(paste('Volume (', units, ')', sep=''))
  return(p)
### a ggplot2 plot.
}, ex = function(){
data(workedexample)
plot_curves(usgs.fd, usgs.pp, usgs.fit, distr='lp3', logscale=TRUE)
plot_curves(usgs.fd, usgs.pp)
plot_curves(curvedata=usgs.fit, distr='lp3')
})
