split_by_wateryear <-
structure(function#Split a timeseries by water year.
### splits a timeseries downloaded using the waterData package by water year.
(d
### a dataframe generated by get_waterdata() and add_wateryear().
){
  # get water years in record
  years = unique(d$WYD %/% 1000)
  # convert data to lists
  dl = vector('list', length=length(years))
  for(i in seq(length(dl))){
     rowmask = d$WYD > years[i]*1000 & d$WYD < (years[i] + 1)*1000
    dl[[i]] = d[rowmask, ]
  }
  names(dl) = paste('wy', years, sep='')
  # turn back into dataframe
  gmtvals = seq(as.Date('0003-10-01'), as.Date('0004-09-30'), by=1)
  yrtable = data.frame(GMT=gmtvals, WYD=seq(366))
  for(n in names(dl)){
    yrdata = dl[[n]]$volume
    dmin = min(dl[[n]]$WYD %% 1000)
    dmax = max(dl[[n]]$WYD %% 1000)
	if(dmin > 1)
	  yrdata = c(rep(NA, dmin - 1), yrdata)
	if(dmax < 366)
	  yrdata = c(yrdata, rep(NA, 366 - dmax))
	yrtable[n] = yrdata
  }
  return(yrtable)
### a dataframe with each column containing data from each 
### water year in the record. Missing values are NA.
}, ex = function(){
#  d = get_waterdata()
#  split_by_wateryear(d)
})
