subset_waterdata <-
structure(function#Subset downloaded USGS flow data.
### subset waterdata by interval.
(d, 
### a dataset generated by split_by_wateryear() or split_by_calendaryear().
sc=c('WYD', 'GMT'), 
### search column to use for subsetting by date.
startdate=NULL, 
### the first day of the interval, either 'MM-DD' string or 3-digit WYD.
enddate=NULL, 
### the last day of the interval, same format as startdate.
na.cols=TRUE
### Logical: remove columns with all values NA?
){
  sc = match.arg(sc, c('WYD', 'GMT'))
  # check startdate, endate
  if(is.null(startdate))
	if(sc == 'WYD')
	  startdate = 1
	else
	  startdate = '10-01'
  if(is.null(enddate))
	if(sc == 'WYD')
	  enddate = 366
	else
	  enddate = '09-30'
  if(sc == 'WYD'){
    # startdate, enddate are integers
	rowmask = d$WYD >= startdate & d$WYD <= enddate
  } else {
    # startdate, enddate are format 'MM-DD'
    startmonth = substr(startdate, 1, 2)
	endmonth = substr(enddate, 1, 2)
    if(substr(d$GMT[1], 1, 4) == '0000'){
	  # data was generated using split_by_calendaryear
	  startyear = '0000'
	  endyear = '0000'
	} else if(startmonth < 10 & endmonth > 9){
	  warning('Intervals spanning September 30 can only be accommodated if',
	          'data is formatted using split_by_calendaryear().')
    } else if(startmonth > endmonth){
	  # interval spans New Years Day (two years)
	  startyear = '0003'
	  endyear = '0004'
	} else {
	  # interval is contained within one year
	  if(endmonth < 10){
	    startyear = '0004'
		endyear = '0004'
	  } else if(startmonth > 9){
	    startyear = '0003'
		endyear = '0003'	  
	  }
	}
	# construct the date intervals
	startinterval = as.Date(paste(startyear, '-', startdate, sep=''))
	endinterval = as.Date(paste(endyear, '-', enddate, sep=''))
	rowmask = d$GMT >= startinterval & d$GMT <= endinterval
  } 
  colmask = rep(TRUE, ncol(d))
  if(!na.cols)
    for(i in seq(ncol(d)))
      if(all(is.na(d[, i])))
        colmask[i] = FALSE 
  return(d[rowmask, colmask])
### a subset of the original dataframe.
}, ex = function(){
#  d = get_waterdata()
#  subset_waterdata(d, startdate='2013-10-01')
})
