add_wateryear <-
structure(function#Add a wateryear column.
### wrapper for get_wateryear() that adds a column named 'WYD' in the second
### column of a dataframe produced by get_waterdata() or get_forecast().
(d
### a dataframe generated by get_forecast() or get_waterdata().
){
  d['WYD'] = to_wateryear(d$GMT)
  othercols = names(d)[!(grepl('GMT', names(d)) | grepl('WYD', names(d)))]
  # return data frame with WYD in second column
  return(d[, c('GMT', 'WYD', othercols)])
### the supplied dataframe, with 'WYD' in second column.
}, ex = function(){
#  d = data.frame(GMT=as.Date(c('2012-10-01', '2013-01-01', '2013-09-30')),
#                 x=c(10,20,30))
#  add_wateryear(d)
})
