get_peakavg <-
structure(function#Calculate peak flow durations.
### get the peak average flows for many flow records.
(d, 
### a dataframe generated by get_forecast() or get_waterdata().
flowduration=c(1,3,7,15,30,60,90,120,183), 
### a vector of window sizes for calculating moving averages.
na.rm=TRUE
### logical: remove NA values prior to calculating peak flow durations?
){
##details<< the function uses the rollmean() function in package 'zoo' to
##compute flow duration timeseries. The maximum value of each averaged
##timeseries is the peak flow for that flow duration.
  peakavg = function(obs, sizes){
	flush.console()
    # helper function to get maximum values from moving window averages
    # get peak flow for each value in sizes
    maxes = rep(NA, length(sizes))
    # take max of each moving window average result
    for(r in seq(sizes))
      maxes[r] = max(rollmean(obs, sizes[r]))
    return(maxes)
  }
  # get flow columns
  cols = names(d)[!(grepl('GMT', names(d)) | grepl('WYD', names(d)))]
  # create results dataframe
  maf = data.frame(flow.duration=flowduration)
  # get maxavg flows for each record
  for(n in cols){
    # remove NA values if na.rm=TRUE
    if(na.rm)
      rec = na.omit(d[,n])
    else
      rec = d[, n]
	# check record length
	maxidx = which(length(rec) < flowduration)[1] - 1
	if(!is.na(maxidx)){
	  # if timeseries is too short, ignore larger flow durations
	  fd = flowduration[seq(maxidx)]
	  placeholders = rep(NA, length(flowduration) - maxidx)
	  cat('Data column', n, 'contains less than', flowduration[maxidx + 1], 
	      'days. Longest flow duration used will be', tail(fd,1), '.\n')
	} else {
	  fd = flowduration
	  placeholders = NULL
	}
	# create the peak average flows table
    maf[n] = c(peakavg(rec, fd), placeholders)
  }
  # transpose data for better table viewing
  maftable = as.data.frame(t(maf[, seq(2, ncol(maf))]))
  names(maftable) = paste(maf$flow.duration, '.day.flow', sep='')
  return(maftable)
### a dataframe.
}, ex = function(){
#  d1 = add_wateryear(get_forecast(as.Date(Sys.time()) ))
#  d2 = split_by_calendaryear(add_wateryear(get_waterdata(startdate='2010-10-01')))
#  get_peakavg(d1, c(1,3,7,15,30,60,90))
#  get_peakavg(d2, c(1,3,7,15), na.rm=TRUE)
})
