plot_trace <-
structure(function#Plot a single ESP trace.
### plot an individual trace.
(d, 
### a dataframe generated by get_forecast() or split_by_*year(get_waterdata() ).
colname
### the column name of the trace to be plotted.
){
  nd = data.frame(GMT=d$GMT, WYD=d$WYD, volume=d[[colname]])
  p = ggplot(nd, aes(x=GMT, y=volume)) + geom_line() + ggtitle(colname)
  return(p)
### a ggplot plot.
}, ex = function(){
#  d1 = add_wateryear(get_forecast(as.Date(Sys.time()) ))
#  d2 = split_by_calendaryear(add_wateryear(get_waterdata()))
#  plot_trace(d1, tail(names(d1), 1))
#  plot_trace(d2, tail(names(d2), 1))
})
