plot_histograms <-
function#Plot histogram and empirical and theoretical densities
### Plot histograms of each flow duration and fitted distribution, with the option of 
### plotting the empirical density function and the L-moment estimated distribution.
(flowdata, 
### flow data generated by get_peakavg().
parameterdata, 
### parameter data produced by refine_parameters()
distr=c('lp3', 'ln3'), 
### theoretical distribution used, either 3-parameter lognormal ('ln3') or log Pearson
### type III distribution ('lp3')
estimatedata=NULL, 
### if not NULL, also plot theoretical distribution using L-moment parameter estimates 
### produced by get_parameters()
empirical=TRUE
### logical: plot the empirical density function?
){
  distr = match.arg(distr, c('lp3', 'ln3'))  
  if(distr == 'lp3'){
    densfunc = dlp3
	datafunc = log10
  } else {
    densfunc = dln3
	datafunc = identity
  }
  plots = list()
  for(n in names(flowdata)){
    plotdata = flowdata[n]
	names(plotdata) = 'flow'
	plotdata['flow'] = datafunc(plotdata$flow)
	plotdata['theoretical'] = datafunc(densfunc(plotdata$flow, 
	                                            parameterdata[[n]][1], 
	                                            parameterdata[[n]][2], 
										        parameterdata[[n]][3]))
    plots[[n]] = ggplot(plotdata,aes(x=flow)) + geom_histogram() + 
	             geom_density()
  }
  return(plots)
}
