replace_zero_flows <-
structure(function#Replace zero values in a dataframe.
### replace numeric values of zero with a specified numeric placeholder.
(d,
### a dataframe generated by get_forecast() or get_waterdata().
r
### the value to substitute, of type numeric.
){
  colmask = !(grepl('GMT', names(d)) | grepl('WYD', names(d)))
  m = as.matrix(d[, colmask])
  m[m == 0] = r
  d[, colmask] = m
  return(d)
### the same dataframe, with all zero values replaced.
}, ex = function(){
#  d = data.frame(x=c(1,2,3), y=c(0, 5, 6), z=c(0,0,9))
#  replace_zero_values(d, 0.001)
#  replace_zero_values(d, 10)
#  replace_zero_values(d, NA)
})
